ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/include/mt-plat \
	-I$(srctree)/drivers/misc/mediatek/sspm/v2 \
	-I$(srctree)/drivers/misc/mediatek/mcupm/include \
	-I$(srctree)/drivers/gpu/mediatek/gpufreq \
	-I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2 \
	-I$(srctree)/drivers/thermal/mediatek \
	-I$(srctree)/drivers/power/supply

obj-$(CONFIG_CHARGER_COOLER_LCDOFF) += charger_cooling_lcdoff.o

