obj-$(CONFIG_TOUCHSCREEN_NT36xxx_HOSTDL_SPI_OEM) += NVT_Touch_HostDL/
obj-$(CONFIG_SND_SMARTPA_AW883XX) += AUDIO/
obj-m += switch_charger/
obj-m += pump_charger/
obj-m += typec/
obj-m += gauge/
obj-m += charge_misc/
obj-y += Panel/
#TN modified by ye.yuan/860593 20231101 TIAIAA-6 begin
obj-m += aw/
#TN modified by ye.yuan/860593 20231101 TIAIAA-6 end
# TN Begin modify by yangyp 20231123 OCALLA-80
obj-$(CONFIG_TINNO_DEVINFO)   += dev_info/
# TN End modify by yangyp 20231123 OCALLA-80
#TS add begin for adding lcd off charger cooling device OCALLA-609 by lgf 20231204
obj-m += thermal/
#TS add end  for adding lcd off charger cooling device OCALLA-609 by lgf 20231204
