ccflags-y += \
		-DAW_HAVE_SNK \
		-DAW_HAVE_SRC \
		-DAW_HAVE_DRP \
		-DAW_HAVE_ACCMODE \
		-DAW_HAVE_EXT_MSG \
		-DAW_HAVE_VDM \
		-DAW_HAVE_DP
obj-m += oem_tcpc_cps8851.o
oem_tcpc_cps8851-objs := \
		cps8851.o

