#include $(srctree)/drivers/misc/mediatek/Makefile.custom
imgsensor_isp6s-objs += $(subdrv-rpath)/s5k4h7yx_mipi_raw_Sensor.o

#ifeq ($(CONFIG_MTK_IMGSENSOR_ISP6S), m)
#obj-$(CONFIG_MTK_IMGSENSOR_ISP6S) += $(MTK_PLATFORM_KO).o
#$(eval $(MTK_PLATFORM_KO)-objs += $(IMGSENSOR_DRIVER_OBJ))
#else ifeq ($(CONFIG_MTK_IMGSENSOR_ISP6S), y)
#obj-$(CONFIG_MTK_IMGSENSOR_ISP6S) += $(IMGSENSOR_DRIVER_OBJ)
#endif
