#ifndef CHARGE_COMMON_H
#define CHARGE_COMMON_H

#include <linux/power_supply.h>

#define DIVIDER1_IINDPM_UA      2100000
#define DIVIDER2_IINDPM_UA      2000000
#define DIVIDER3_IINDPM_UA      1000000
#define DIVIDER4_IINDPM_UA      2400000

#define BAT_CYCLE_COUNT_LEVEL1  150
#define BAT_CYCLE_COUNT_LEVEL2  1020
#define BAT_CYCLE_COUNT_LEVEL3  1050
#define BAT_MAINT_CHARGE_CV1_UV 4500000
#define BAT_MAINT_CHARGE_CV2_UV 4450000
#define BAT_MAINT_CHARGE_CV3_UV 4330000
#define BAT_MAINT_GAUGE_VOL0_MV 4520
#define BAT_MAINT_GAUGE_VOL1_MV 4460
#define BAT_MAINT_GAUGE_VOL2_MV 4400
#define BAT_MAINT_GAUGE_VOL3_MV 4300

//same with kernel-5.10/drivers/power/supply/mtk_chg_type_det.c
enum attach_type {
	ATTACH_TYPE_NONE,
	ATTACH_TYPE_PWR_RDY,
	ATTACH_TYPE_TYPEC,
	ATTACH_TYPE_PD,
	ATTACH_TYPE_PD_SDP,
	ATTACH_TYPE_PD_DCP,
	ATTACH_TYPE_PD_NONSTD,
};

enum ext_charger_type {
	POWER_SUPPLY_TYPE_USB_HVDCP = POWER_SUPPLY_TYPE_WIRELESS + 10,
	POWER_SUPPLY_TYPE_USB_OTHER = POWER_SUPPLY_TYPE_WIRELESS + 11,
	POWER_SUPPLY_TYPE_USB_DIVIDER1 = POWER_SUPPLY_TYPE_WIRELESS + 12,
	POWER_SUPPLY_TYPE_USB_DIVIDER2 = POWER_SUPPLY_TYPE_WIRELESS + 13,
	POWER_SUPPLY_TYPE_USB_DIVIDER3 = POWER_SUPPLY_TYPE_WIRELESS + 14,
	POWER_SUPPLY_TYPE_USB_DIVIDER4 = POWER_SUPPLY_TYPE_WIRELESS + 15,
};

#endif
